### ISSUE TITLE
Architecture RESEARCH

### ISSUE THREAD

**Issue by boiche** [boiche/Belot#24]
So far the architecture consists of basic client-server approach, where the client initiates protocol switch to websocket, thus creating new communication channel. Single game contains up to 4 persistent websocket connections.

This architecture needs a revision.

- [ ] Should the server be distributed to smaller services
- [ ] Research stress scenarios (100 simultaneous games)
- [ ] Find health check platform
- [ ] Consider modular monolith (future approach for better scalability)

**Comment by stanislavstoyanov99** [comment]
For heatlh checks we can use: https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-9.0
