### ISSUE TITLE
SignalR: connectivity

### ISSUE THREAD

**Issue by boiche** [boiche/Belot#8]
### Description:
It will be handy if SignalR connections have prolonged lifetime. This will give players time to rejoin left games.

### Requirement:

- [ ] - UI for actively playing games: button to rejoin
- [ Persistent connections: find a way to preserve them (currently when leaving a game connections automatically close)]
- [ ] Time violation: when a player fails to rejoin after **x** time violations #6 close connection and provide a bot #7 to continue the game.
- [ ] - Reward restrictions: when player is suspended from a game, no rewards to be given to the player only (the teammate will receive if victorious)
